### ISSUE TITLE
Choreographic for music in the wild

### ISSUE THREAD

**Issue by zhangsanfeng86** [jw09191/MNET#1]
Hi， 
Could you share some demo video on Choreographic for music in the wild?

**Comment by jw09191** [comment]
Hello @zhangsanfeng86,

We plan to show more examples including wild music on the project page (https://jw09191.github.io/MNET_CVPR22/).

Thanks.

**Comment by jw09191** [comment]
Hello @zhangsanfeng86,

We plan to show more examples including wild music on the project page (https://jw09191.github.io/MNET_CVPR22/).

Thanks.
